### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by Facj** [heartsucker/node-deb#109]
Hello!

I am trying to use node-deb for the first time and I have run into this error.
It seems that there is a deprecaton issue with one of the dependencies.
How can I solve it?

```
npm\node_modules\winston\lib\winston\common.js:26
      throw new Error([
      ^

Error: { cli } was removed in winston@3.0.0.
Use a custom winston.format = winston.format(function) instead.
    at Object.cli (C:\Users\fcastro.NORVENTO\AppData\Roaming\npm\node_modules\winston\lib\winston\common.js:26:13)
    at Object.<anonymous> (C:\Users\fcastro.NORVENTO\AppData\Roaming\npm\node_modules\jq\bin\jq:30:9)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**Comment by heartsucker** [comment]
This seems to be a problem with your node installation, but I cannot be certain. This project does not depend on winston (or anything for that matter) as it's only written in bash.
